trigger:
- master
- rel/*

pr:
- master
- rel/*

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: windows-latest

    variables:
      BuildConfiguration: Release

    steps:
    - task: DotNetCoreCLI@2  
      inputs:
        command: custom
        custom: tool
        arguments: install --tool-path . nbgv
      displayName: Install NBGV tool

    - script: nbgv cloud
      displayName: Set Version

    - task: DotNetCoreCLI@2
      inputs:
        command: pack
        packagesToPack: src/AClassLibrary/AClassLibrary.csproj
        configuration: $(BuildConfiguration)
        packDirectory: $(Build.ArtifactStagingDirectory)\Packages    
        verbosityPack: Minimal
      displayName: Build Package

    - publish: $(Build.ArtifactStagingDirectory)\Packages   
      displayName: Publish Build Artifacts  
      artifact: BuildPackages
      
- stage: CodeSign
  condition: and(succeeded('Build'), not(eq(variables['build.reason'], 'PullRequest')))
  jobs:
  - deployment: CodeSign
    displayName: Code Signing
    pool:
      vmImage: windows-latest    
    environment: Code Sign - Approvals
    variables:
    - group: Sign Client Credentials
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          
          - download: current
            artifact: BuildPackages
          
          - powershell: ./scripts/Sign-Package.ps1
            displayName: Sign Packages
            env:
              SignClientUser: $(SignClientUser)
              SignClientSecret: $(SignClientSecret)
              ArtifactDirectory: $(Pipeline.Workspace)/BuildPackages
              
          - publish: $(Pipeline.Workspace)/BuildPackages
            displayName: Publish Signed Packages
            artifact: SignedPackages

- stage: CI
  jobs:
  - deployment: CIJob
    pool:
      vmImage: windows-latest
    environment: Azure Artifacts
    strategy:
      runOnce:
        deploy:
          steps:          
          - download: current
            artifact: SignedPackages
          
          - task: NuGetCommand@2
            displayName: NuGet Push
            inputs:
              command: push
              packagesToPush: $(Pipeline.Workspace)/SignedPackages/*.nupkg
              publishVstsFeed: '96789f1c-e804-4671-be78-d063a4eced9b/73594112-df72-493e-8bae-53ffeca0b6a2'