trigger:
- master
- rel/*

pr:
- master
- rel/*

jobs:
- job: Build
  pool:
    vmImage: windows-latest

  variables:
    BuildConfiguration: Release

  steps:
  - task: DotNetCoreCLI@2  
    inputs:
      command: custom
      custom: tool
      arguments: install --tool-path . nbgv
    displayName: Install NBGV tool

  - script: nbgv cloud
    displayName: Set Version

  - task: DotNetCoreCLI@2
    inputs:
      command: pack
      packagesToPack: src/AClassLibrary/AClassLibrary.csproj
      configuration: $(BuildConfiguration)
      packDirectory: $(Build.ArtifactStagingDirectory)\Packages    
      verbosityPack: Minimal
    displayName: Build Package

  - task: PublishPipelineArtifact@0
    displayName: Publish Build Artifacts  
    inputs:
      targetPath: $(Build.ArtifactStagingDirectory)\Packages      
      artifactName: BuildPackages

